### ISSUE TITLE
Use Traits for the important types?

### ISSUE THREAD

**Issue by theduke** [hyperium/http#122]
Currently, the important types like Request, Response and Builder are just structs.

This limits any possibility for extension and customization considerably, since the only way to extend anything is to use a wrapper type.

Has it been considered to also define **traits** for those types, and provide structs with a default implementation?

This would open the possibility of using extension traits.

One such use case would be reqwest and it's convenience methods for json and form handling.

**Comment by carllerche** [comment]
IMO, the ergonomic overhead of traits is not worth it. There is an extension map already that allows custom extensions and convenience methods can be added w/ traits as well (without needing to write your fns over generics).

If there are specific cases that aren't handled by this, then we can evaluate that.

**Comment by carllerche** [comment]
There hasn't been any further discussion here, so I am going to close due to inactivity.

However, anyone feels there is value in providing traits, I urge them to explore that space in a separate repo. Then, there will be something more concrete to discuss as well as a feel for how it would play out.
