### ISSUE TITLE
Add a `HeaderName::from_static` method

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#168]
This would be similar to the `HeaderValue::from_static`, panicking instead of returning a `Result`.

If it's possible for the static slice to be used instead of copying it, that'd be bonus points.

**Comment by smithsps** [comment]
As all header names are represented as lower case, how should a static strings with uppercase characters be handled with regards to using the static slice vs copying? 

I couldn't decide on the best approach out of these four:

1. Panicing/Warning on uppercase. As it is already panicing on errors, it could require that all passed strings to be lowercase. This would always allow the use the static slice rather than copying, however its probably most annoying to users. 

1. Ignoring case. It can always copy and convert to lowercase as is done in HeaderName::from_bytes.

1. Strict Hybrid. Combining options 1 and 2: On header strings of less than 64 it could ignores case and always copy the string. With strings of >=64 it could panic and require all characters to be lowercase.

1. Compatibility Hybrid. Scan if the static strings have uppercase characters and then appropriately use the static slice or copying as needed.

**Comment by seanmonstar** [comment]
I'd personally prefer either 1 or 4, perhaps leaning towards 1 since it's a static string. @carllerche?

**Comment by carllerche** [comment]
I would go with 1: panic. This is the strategy used elsewhere. Switching to 4 at a later time if this is wrong is not a breaking change.

**Comment by seanmonstar** [comment]
Done in #195

**Comment by katie-martin-fastly** [comment]
:wave: Hello! Would a PR to switch to option 4 described above, copying the string when capital letters are found, be a welcome change? I have found this panic behavior confusing in the past, and don't believe that I'm alone in that experience.

I saw your comment [here](https://github.com/hyperium/http/issues/228#issuecomment-404996755) that says:

> As you've pointed out, RFC 7230 says names are case-insensitive**[...]** Additionally, in HTTP/2, all header names are lowercase (it's specified to be a protocol error for upper case names). Because of this, HeaderName chooses to always handle names as lower case. Doing this allows optimizations [that improve the] speed of inserts and searches in the HeaderMap.

I'd like to first be clear that I agree with internally lower-casing header names for these performance optimizations, have no intention of asking for that behavior to change, and thank you for maintaining such a wonderful crate here. :heart:

That said, HTTP/1 doesn't enforce these same guidelines about upper-casing, only that the names are case insensitive<sup>[1]</sup>. A header name like `Location` or `Content-Type` is not invalid under HTTP/1. Many people camel-case header names by convention, and many code examples in this repository do so as well.

What makes `HeaderName::from_static` confusing, in my experience, to work with is that it has different behavior from `try_from`.  The `README` for example, shows use of the `request::Builder::header` and `response::Builder::header` methods, which implicitly lowercase their arguments.

I believe that this happens [here](https://github.com/hyperium/http/blob/b00473c3ec942c03de55e47af1070b16a9dd23d8/src/header/name.rs#L1669), because the [HEADER_CHARS](https://github.com/hyperium/http/blob/b00473c3ec942c03de55e47af1070b16a9dd23d8/src/header/name.rs#L981) constant will map these letters into lowercase format. Conversely, `from_static` will panic for the same input, as it uses [HEADER_CHARS_H2](https://github.com/hyperium/http/blob/b00473c3ec942c03de55e47af1070b16a9dd23d8/src/header/name.rs#L1012), finds a `0`  and then panics.

```
// returns `Ok(..)`
assert!(HeaderName::try_from("X-Custom-Foo").is_ok());

// panics
let _ = HeaderName::from_static("X-Custom-Bar");
```

As mentioned above, switching to an approach that copies the string when needed wouldn't be a breaking change. I believe that if the [documentation](https://docs.rs/http/0.2.1/http/header/struct.HeaderName.html#method.from_static) was appropriately updated, we could also be clear that uppercase literals would be copied internally.

I would be more than happy to implement this, if it would be a welcome change, but I wanted to ask before providing a patch. And again, in closing, thanks for your work maintaining `http` :love_letter: 

[1]: https://tools.ietf.org/html/rfc2616#section-4.2

**Comment by seanmonstar** [comment]
I guess the point is that there's an assumption that `from_static` can actually use the static string. I'm hopeful we can eventually make that function a `const fn`. But if it needed to make a copy to the heap and lowercase it, the function could no longer be `const fn`.

The docs of the function *do* point out it needs to be lowercase. Perhaps we could adjust the panic situation to notice when it would have been valid if lowercase?

**Comment by katie-martin-fastly** [comment]
Thank you for explaining the background regarding `const`ness, that's a helpful factor in reasoning about this. I agree, a better panic message in cases where the lowercase string would be a valid `HeaderValue` would be a helpful addition. Would a patch to that effect be welcome?

**Comment by seanmonstar** [comment]
That sounds like a fine idea!
