### ISSUE TITLE
What's the plan for interoperability with other http clients?

### ISSUE THREAD

**Issue by kbacha** [hyperium/http#183]
When I read about and worked on this crate I felt like one of the big advantages of having the types removed from the client libraries is that I can potentially write a client library around the http interface without being dependent on the transport client explicitly. One example where this is useful is around the hyperium vs reqwest divide. Both utilize request and response types but they are different and if i make a sync vs async client library it's hard to exchange the transport.

So, my question is, what's the path towards making this library at least part of those? This concerns me as I want to use it as an interface between transport and resources for my work on https://github.com/kbacha/stellar-sdk

Thanks!

**Comment by seanmonstar** [comment]
- The hyper library will transition all of its types to those from this crate in the 0.12 release.
- Reqwest will also transition to the new types, probably a little after, since it'd need to pass them to hyper internally. I do suspect that `reqwest::{Request, RequestBuilder, Response}` will stay as distinct types, since they provide extra features on top, with conversion methods to the types from this crate.

**Comment by sagebind** [comment]
It would be nice if the extra features could be implemented as extra traits in reqwest. That's what I've been trying to do on all of my http-related code. The `extensions()` API is pretty great for this; create an extension trait for any convenience methods, and if you need to store extra state, use an extension in combination with the extension trait.

**Comment by kbacha** [comment]
Gonna close this since it's in the cards 😄
