### ISSUE TITLE
Modification of Uri's components in place

### ISSUE THREAD

**Issue by DoumanAsh** [hyperium/http#189]
This may be surprising but I had need to modify part of Uri. Specifically path as I'd like to normalize it before it would be passed to router.

I suspect there might be a reason why there are no mutable references for Uri's components so before I'd go for PR, I'd like to hear whether it would be appropriate to add API to get mutable components of Uri for in place modification.
Currently I need to create entirely new Uri for that unless I'm missing something...

**Comment by seanmonstar** [comment]
What I've done myself is to convert into `uri::Parts`, and then just change the part I needed to. But it likely needs an easier way!

The problem is that `Uri` enforces the correct syntax on the underlying buffer, so we can't just allow pushing or inserting arbitrary strings. A thought I had was that we could offer a Builder API, and allow converting an existing `Uri` into a `Builder`. I think it's more natural that way to have methods like `path_segment` or whatever that can take strings, and the builder can return an error if the string has illegal characters.

What would you think of that?

**Comment by kbacha** [comment]
I would love a `uri::Builder`! Especially for adding/removing/modifying query params. I was considering writing up a ticket around the query params and potentially the specification of a vec of tuples. I think that `reqwest` may currently support that and I was missing it recently when working with the `Uri` type in `http`.

**Comment by DoumanAsh** [comment]
@seanmonstar Hmm, from what I can see `Uri` consist of separate parts that should be independent of each other so I don't understand what would be a problem.
Or is there some extra validation done to put some restraints on parts?

Originally i was thinking of allowing to have set of methods like `set_<part>`, but having a builder that would accept original `Uri` is fine too.
Currently I need to do some work with extra allocations:
```
let mut new_parts = uri::Parts::default();
new_parts.scheme = url.scheme_part().cloned();
new_parts.authority = url.authority_part().cloned();
new_parts.path_and_query = Some(path);
```

**Comment by seanmonstar** [comment]
@DoumanAsh oh, you mean being able to replace, say, the `path_and_query` completely, not modifying it like with a `push_str` method?

You could convert the `Uri` you have with `uri.into_parts()`, and then modify them, instead of creating a new one. However, even creating a new one isn't allocating brand new copies, since the parts internally have `Bytes`, which are ref-counted immutable slices.

**Comment by DoumanAsh** [comment]
Yes, my idea was replacing existing parts because normally you wouldn't want to create completely new URI from existing one.

In my case though I'm limited by the fact that my uri is available only as `&mut URI`

So on what API you wish to settle?

**Comment by seanmonstar** [comment]
The existence of certains parts also has meaning, so for instance, if you received `GET /foo/bar HTTP/1.1`, that'd mean you have a `Uri` or `/foo/bar`. Internally, that'd be something like `Uri { scheme: None, authority: None, path_and_query: Some("/foo/bar"), }`. What happens if you tried to insert the host of your server there?

```rust
uri.set_authority(Authority::from_static("example.local"));
```

Now you have `Uri { scheme: None, authority: Some("example.local"), path_and_query: Some("/foo/bar"), }`. What even is that? `example.local/foo/bar`? That's not a valid request-target. It doesn't match any of the 4 variants (origin-form, absolute-form, authority-form, or asterisk-form).

So, I think it'd be safer to have to put the mutations on a type that can re-check the validity of the value. For that reason, my personal feeling is mutating should require converting to `Parts` (which has validation back to `Uri`), or an easier to use `Builder`.

**Comment by DoumanAsh** [comment]
Personally I feel that it is user responsibility to create URI that makes sense.
The only thing `http` should do is to ensure that URI is valid from RFC point of view.

Would you like me to write PR following your suggestion on converting to `Parts`?

**Comment by seanmonstar** [comment]
> The only thing http should do is to ensure that URI is valid from RFC point of view.

Right, and what I was saying is that variant is not a legal request-target at all.

> Would you like me to write PR following your suggestion on converting to Parts?

Sorry, which suggestion exactly?

**Comment by DoumanAsh** [comment]
>Right, and what I was saying is that variant is not a legal request-target at all.

Ah I see, I didn't check RFC in details so I guess I see now how you can wreck your `Uri` like that

>For that reason, my personal feeling is mutating should require converting to Parts (which has validation back to Uri)

This^

**Comment by seanmonstar** [comment]
You can already convert a `Uri` into `Parts`, mutate, and then try to convert back.

I'm all for things being easier/better, though! What specifically were you thinking? Like the builder idea?

**Comment by DoumanAsh** [comment]
Ah yeah, apologies. I totally lost track of our discussion here.
Since mutating in place is not option and we already have way to convert back and fourth I believe there is no need to add extra utilities.
