### ISSUE TITLE
Panic in Uri::from_str(&Uri::from_str(x).to_string()) found by fuzzer

### ISSUE THREAD

**Issue by killercup** [hyperium/http#197]
In <https://github.com/rust-fuzz/targets/pull/113>, I added some simple fuzzers for parts of this crate. To test `Uri::from_str`, I added this code:

```rust
pub fn fuzz_http_uri(data: &[u8]) {
    use std::str;
    use std::str::FromStr;

    if let Ok(text) = str::from_utf8(data) {
        if let Ok(uri) = http::uri::Uri::from_str(text) {
            http::uri::Uri::from_str(&uri.to_string()).unwrap();
        }
    }
}
```

- Is this a correct assertion to make?
- This panics with `b"S"` as an input

**Comment by seanmonstar** [comment]
This probably a correct assertion, since it's just check that a new `Uri` can be parsed from `uri.to_string()`, which should likely be the case.

I *bet* the error is that an incorrect insertion of a path, meaning it went `"S"` -> `"S/"`, and then the second parse fails. That's because the first time, it just saw the 1 letter, and parsed as an authority-form. But then when it saw the path, without a scheme in the beginning, that isn't any of the 4 valid forms.
