### ISSUE TITLE
Adopt the Body type from the http-service crate

### ISSUE THREAD

**Issue by jimmycuadra** [hyperium/http#298]
A while back I opened [this issue](https://github.com/rust-lang-nursery/wg-net/issues/84) to discuss the problem of building libraries that are agnostic to HTTP client, and there is now a crate developed by the web services working group intended to solve this problem: [http-service](https://github.com/rust-net-web/http-service). It introduces a `Body` type that is intended to replace the generic type currently used for `http::{Request, Response}`.

I'm sure the working group was going to be in touch to discuss this with you, and maybe they already have, but I wanted to get a tracking issue up so I could follow progress on integrating this new crate with `http`.

/cc @aturon @yoshuawuyts

**Comment by carllerche** [comment]
Thanks for the suggestion.

This crate avoids any restriction on the body type by design. The goal of the crate is to provide HTTP types that universally make sense. The body type is opinionated. At the very least, you have to pick between synchronous and asynchronous.

Given this, the `http` crate will not adopt the referenced body type.
