### ISSUE TITLE
`HeaderMap::Drain` can cause data race

### ISSUE THREAD

**Issue by Qwaz** [hyperium/http#355]
https://github.com/hyperium/http/blob/9c05e391e00474abaa8c14a86bcb0fc5eff1120e/src/header/map.rs#L2099-L2102

`HeaderMap::Drain` implements `Iterator` trait with `Item = (HeaderName, ValueDrain<'a, T>)`. This definition makes it possible to create multiple mutable references to the underlying `HeaderMap` by creating multiple `ValueDrain`, because there is no relation between the lifetime of `&mut self` and the returned `ValueDrain`.

This bug may invalidate `ValueDrain` iterators or make them return incorrect results. In multi-threaded scenario, the bug allows multiple threads to mutate underlying `Vec` at the same time, which I believe exploitable. However, I expect no code is sending `ValueDrain` to the other thread in practice.

[Demonstration](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f61a445dd5dca1f5516b540f74330d8b)

**Comment by seanmonstar** [comment]
Yea, the call to `extra_values.swap_remove` isn't synchronized, so that's a problem. I think the solutions both have downsides, but I'll list them out:

- **Remove the `impl Send for ValueDrain`**, but this is an API breaking change. I suspect this should be incredibly uncommon. Perhaps the only sort of way someone would be affected is if using `rayon::par_iter` or similar with this.
- Put a `Mutex` into the `ValueDrain`. This negatively affects everyone for such a rare occurrence.
- **Re-write the internals of `HeaderMap` to not store all extra values in a single `Vec`.** This seems like the worst option, as it will take longer to do, and also negatively impacts memory usage and fragmentation.
