### ISSUE TITLE
Method::from_* are accepting anything

### ISSUE THREAD

**Issue by chapa** [hyperium/http#402]
Hello,

Is it normal that `Method::from_bytes()` and `Method::from_str()` returns `Ok` no matter the input ? :thinking:

This code compiles and runs without any error :
```rust
use http::Method;
use std::str::FromStr;

fn print_method(method: Method) {
    println!("This is a http::Method struct : {:?}", method);
}

fn main() {
    let method_from_bytes = Method::from_bytes(b"fewokpoekwopf").unwrap();
    let method_from_str = Method::from_str("fewokpoekwopf").unwrap();
    
    print_method(method_from_bytes);
    print_method(method_from_str);
}
```
```
This is a http::Method struct : fewokpoekwopf
This is a http::Method struct : fewokpoekwopf
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cd2b54be1d7fd978d2731633a04dd5ac)

I would like to construct a `Method` from the user input so I was expecting an `Err` if the given string doesn't match a valid HTTP method, looks like it doesn't work how I expected.

**Comment by seanmonstar** [comment]
Those values are valid HTTP methods. If they contained illegal characters, an error would have been returned.

**Comment by chapa** [comment]
So a valid HTTP method is any string ?

How can I do to expect only [real world](https://tools.ietf.org/html/rfc7231#section-4.1) HTTP methods ? Is it out of the scope of this library ?

Actually I realize it is the same for status codes, any number between 100 and 599 is accepted, I'm a bit confused why ?

**Comment by seanmonstar** [comment]
Not just any string. It can only contain letters, no other characters or spaces. This is because the HTTP spec defines what a method can be, in case new ones are invented, and in fact some systems use such methods, like "PROPTEST".

Status codes are also defined as a 3 digit number between 100 and 599. New status codes get added, and if we only allowed the ones we knew about at the time, users couldn't talk to websites that get new features, such as 103, or 308.

**Comment by chapa** [comment]
Ok, I didn't know people could use non standard HTTP methods like that. I guess I'll have to validate it myself :wink:
