### ISSUE TITLE
Prefer TryInto over TryFrom in builders

### ISSUE THREAD

**Issue by SmolPatches** [hyperium/http#727]
I have been looking at the API for this crate as someone relatively new to Rust.
Amongst the code, I noticed this method deceleration for the requests::Builder struct
```rust
pub fn method<T>(self, method: T) -> Builder
where
    Method: TryFrom<T>,
    <Method as TryFrom<T>>::Error: Into<Error>,
```
Initially I was confused as to the reasoning that a constraint on `Method` was defined here.
Since `Method` seems to be unused in the function signature.
After looking deeper I realize the point of this constraint is to limit `T` to values that can be converted to `Method::try_from`. 
Is there any reason that the where clause doesn't use the reciprocal trait `TryInto` instead?
For example,
```rust
pub fn method<T>(self, method: T) -> Builder
where
    T TryInto<Method>,
    <T as TryInto<Method>>::Error: Into<Error>,
```
Idk about others but this would have been clearer to me.
I was curious if there was a reason as to why the original was chosen over this second solution, which I think is more clear(imo).

**Comment by seanmonstar** [comment]
I can't honestly remember why this style was chosen. I thought it was because of the way `From` and `Into` played together, but it works the opposite to what would be supported with this syntax: all `impl From` automatically implement `Into`, but not the reverse. That's why libstd recommends:

> Prefer using [Into](https://doc.rust-lang.org/std/convert/trait.Into.html) over using From when specifying trait bounds on a generic function. This way, types that directly implement [Into](https://doc.rust-lang.org/std/convert/trait.Into.html) can be used as arguments as well.

So, it would indeed be better to switch them all to `TryInto`.

Would you like to submit a PR doing so?

**Comment by SmolPatches** [comment]
Sure I'd be up for submitting a PR!
